[package]
name = "advent_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="day1_p1"
path="src/day1/part1.rs"

[[bin]]
name="day1_p2"
path="src/day1/part2.rs"
